[package]
name = "assignment1"
version = "0.1.0"
authors = ["iss_ghumman <iss.ghumman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.16"
async-std = "1.9.0"